- name: Configure EC2 instance
  hosts: ec2-instance
  become: yes
  tasks:
    - name: Update packages
      apt:
        update_cache: yes

    - name: Install apache2
      apt:
        name: apache2
        state: present

    - name: Start apache2
      service:
        name: apache2
        state: started

